import type { Config } from "@netlify/functions";
import { decodeJwt } from "jose";
import { z } from "zod";
import { getLicense, isRevoked, getActivation, setActivation, readBody, json } from "./_lib";

const schema = z.object({
  token: z.string().min(10),
  machine_id: z.string().min(8),
});

export default async function handler(req: Request) {
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const body = schema.safeParse(await readBody(req));
  if (!body.success) return json({ error: "Payload invalide" }, 400);

  const { token, machine_id } = body.data;

  // Decode JWT (no signature verify — la présence en base confirme qu'on l'a émise)
  let jti: string;
  let email: string;
  try {
    const claims = decodeJwt(token);
    jti = String(claims.jti ?? "");
    email = String(claims.sub ?? "");
    if (!jti || !email) throw new Error("missing claims");
    if (claims.exp && claims.exp * 1000 < Date.now()) {
      return json({ error: "Licence expirée" }, 400);
    }
  } catch {
    return json({ error: "Token invalide" }, 400);
  }

  // Confirm license was generated by us
  const license = await getLicense(jti);
  if (!license) return json({ error: "Licence introuvable" }, 404);

  if (await isRevoked(jti)) {
    return json({ error: "Licence révoquée" }, 403);
  }

  const existing = await getActivation(jti);
  if (existing) {
    if (existing.machine_id === machine_id) {
      // Same instance — OK (redéploiement/reinstall)
      return json({ ok: true, already: true });
    }
    return json(
      {
        error: "Cette licence est déjà activée sur une autre instance.",
        hint: "Désactive-la depuis l'ancienne instance (Réglages → Licence), puis réessaie.",
      },
      409,
    );
  }

  await setActivation(jti, machine_id, email);
  return json({ ok: true });
}

export const config: Config = { path: "/api/activate" };
